spring.application.name=sistema_inventario_api
server.port=8080

#credenciales para base de datos

spring.datasource.url=jdbc:postgresql://localhost:5432/BD_sistema_inventario
spring.datasource.username=postgres
spring.datasource.password=12345678



# el driver
spring.datasource.driver-class-name=org.postgresql.Driver


# para ver el sql en los comandos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect